name: Deploy Docker Image to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t your-docker-image-name .
        docker tag your-docker-image-name your-dockerhub-username/your-docker-image-name:latest
        docker push your-dockerhub-username/your-docker-image-name:latest

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy Docker image to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
        docker pull your-dockerhub-username/your-docker-image-name:latest
        docker stop $(docker ps -a -q) || true
        docker run -d -p 80:80 your-dockerhub-username/your-docker-image-name:latest
        EOF