
name: Deploy Docker Image to EC2

on: 
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1. Checkout Repository
    - name: Checkout repository
      uses: actions/checkout@v4

   #- name: Set up Docker Buildx
   #   uses: docker/setup-buildx-action@v3

      # Step 2. Login to Dockerhub
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_PASSWD }}
        password: ${{ secrets.DOCKERHUB_USERNAME }}

      # Step 3. Build and push Docker image
    - name: Build and push Docker image
      working-directory: ./app
      run: |
        docker build -t app-image .
        docker tag app-image crsxyrus/app-image:latest
        docker push crsxyrus/app-image:latest
