
name: Deploy Docker Image to EC2

on: workflow_dispatch
  #push:
    #branches:
      #- dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1. Checkout Repository
    - name: Checkout repository
      uses: actions/checkout@v4

   #- name: Set up Docker Buildx
   #   uses: docker/setup-buildx-action@v3

      # Step 2. Login to Dockerhub
    - name: Login to DockerHub
      uses: docker/login-action@v3
      run: echo "${{ secrets.DOCKERHUB_PASSWD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Step 3. Build and push Docker image
    - name: Build and push Docker image
      working-directory: ./app
      run: |
        docker build -t app-image .
        docker tag app-image crsxyrus/app-image:latest
        docker push crsxyrus/app-image:latest

      
     #- name: Install SSH Key
     # uses: webfactory/ssh-agent@v0.9.0
     # with:
     #  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

     #- name: Deploy Docker image to EC2
     # run: |
     #   ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
     #   docker pull your-dockerhub-username/your-docker-image-name:latest
     #   docker stop $(docker ps -a -q) || true
     #   docker run -d -p 80:80 your-dockerhub-username/your-docker-image-name:latest
     #   EOF